### ISSUE TITLE
Console Error + Suggestions

### ISSUE THREAD

**Issue by Corcustos** [TheFlash787/Mobpression#1]
Not sure what is causing but, but I randomly get [this](https://pastebin.com/BiQw95QG) error spammed in my console due to this plugin. I'm using the latest version of the plugin, SpongeForge 3616, and forge 2809. Unfortunately I do not have any extra information to give as I can't pinpoint exactly what causes it and I don't see any direct interference in-game. I am also using Pixelmon 7.0.6 if that matters, since I'm not sure how this plugin treats the pixelmon themselves.

As for the suggestion, after you add a config, I think a good config option in addition to the blacklist you're planning is a radius option so you can choose how close you want mobs to be before they merge themselves. Right now it seems like they have to actually touch each other to merge. Also, if not already planned, I think that it would be even more beneficial if we could set certain mobs to not merge until a certain threshold is met. This way I can set the threshold to, say, 5, which would allow players to have 2 pairs of mobs for breeding or 4 individual golems until they started merging.

Overall, very useful plugin. I'm really surprised something like this wasn't already publicly available. Helps prevent players from having a ridiculous amount of entities loaded, which is very much appreciated.

EDIT: I have just received a [new error](https://pastebin.com/MRgVHY1s), this time with a crash. This is happening repeatedly and has led to me having to remove Mobpression. It would seem the issue has elevated in severity.

**Comment by TheFlash787** [comment]
Hey! I apologise for the delay in getting to you. I completely forgot that I had issues available for people to use! 

I agree with your suggestions and I will add them onto my list of things to do with regards to Mobpression. And with the issue you're encountering, did this occur immediately?

Also, I notice you're running version **1.0.1** and we have **1.0.2** available which *does* change how the caching of the mobs work and will fix that issue for you, including the "Entity no longer exists! Removing it from the map" messages which will no longer appear. Please can you also see if the second issue is present with this version.

https://ore.spongepowered.org/TheFlash787/Mobpression/versions/1.0.2-SNAPSHOT/download/

Thank you!

**Comment by Corcustos** [comment]
At the time of creating the issue, 1.0.1 was the latest. The issue I ran into did not happen immediately, but from what I can tell I'm not experiencing it in 1.0.2. However, this testing was very brief, and I will let you know if something happens again as it was rather sudden and I was unable to forcefully reproduce it in the last version.

**Comment by TheFlash787** [comment]
Alrighty. Here is a further updated jar file which you can test. However since you have not reported back with any further issues, I think we can safely say that this has been fixed. Please let us know if you experience any more issues!

Thank you.

[Mobpression.zip](https://github.com/TheFlash787/Mobpression/files/3537258/Mobpression.zip)

**Comment by Corcustos** [comment]
> Alrighty. Here is a further updated jar file which you can test. However since you have not reported back with any further issues, I think we can safely say that this has been fixed. Please let us know if you experience any more issues!
> 
> Thank you.
> 
> [Mobpression.zip](https://github.com/TheFlash787/Mobpression/files/3537258/Mobpression.zip)

You are correct in assuming that I have not experienced any issues since then. I do have a question, however. Regarding the minimum threshold, which scenario is true, using 5 as the threshold for compressing?:

1. Mobs reach 5 within X Radius > Mobs Merge into 1, leaving only 1 behind. > Process repeats, making it difficult to maintain 4 mobs because when you breed one they all merge into 1 entity, ending the breeding cycle.
2. Mobs reach 5 within X radius > Mobs merge until there is 4 within said Radius > Merging will continue happening only when there are more than 4, distributing mobs to the lowest mob stack or random if all are equal, and will always leave at least 4 behind.

The second behavior is what I was aiming for when I suggested a minimum threshold as the first behavior, while improving the situation a bit, just slightly delays the issue I'm encountering.
