### ISSUE TITLE
Small plugin review

### ISSUE THREAD

**Issue by XakepSDK** [TheFlash787/Mobpression#2]
1. Use iterators to remove items from collection.
2. There is no need to run your task asynchronously, it may lead to errors
3. Databasehandler is not portable across various systems. Use `path#toUri` to make portable URI, then you can use `uri#getPath` to get path part as string.

**Comment by TheFlash787** [comment]
Hey! Thank you for doing this, it really helps. I have applied your suggested changes and they can be seen through the latest commits. Please do let me know if you find anything else!

Sorry for the delay, also. I hadn't realised that issues were made, I didn't see any email, lol. 
Thank you! :heart:
