### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by axin0452** [TheFlash787/Mobpression#3]
Can you add a minimum merge option?

When the number of animals in the block reaches a certain level, the merging operation will take place.

**Comment by TheFlash787** [comment]
Hey! I'll definitely look into this for you and I'll keep you updated. Somebody else requested the same thing! (#1).

Thank you! :heart:

**Comment by axin0452** [comment]
How long will it take to update the new features?

**Comment by TheFlash787** [comment]
Hey! Sorry for not getting to you sooner. I’ve had a look at this and have implemented the configuration option and the mechanic itself. However whilst it’ll block any compressions below a certain amount, it will only compress the mobs if they are all touching at the exact same time (i.e. if you have 5 cows all touching eachother, they will all compress together, assuming you set the minimum compression to be 5). Tomorrow morning, I will push this update to Ore and I’ll respond back here just to let you know. 

Thank you, and sorry again!

**Comment by axin0452** [comment]
When to update to ore?I can't wait.

**Comment by TheFlash787** [comment]
Hey! I can't upload to Ore because I've just updated my PGP signing key (I must wait 3 days). However, here is the updated file. You'll want to refresh your configuration file when installing. Thanks!
[Mobpression.zip](https://github.com/TheFlash787/Mobpression/files/3537253/Mobpression.zip)

**Comment by axin0452** [comment]
No configuration files,The config/mobpression/  folder is empty!
