### ISSUE TITLE
Server could not start

### ISSUE THREAD

**Issue by axin0452** [TheFlash787/Mobpression#8]
[2019-09-03-1.log.gz](https://github.com/TheFlash787/Mobpression/files/3569560/2019-09-03-1.log.gz)
Mobpression-1.0.3-SNAPSHOT.jar
forge-1.12.2-14.23.5.2838-universal.jar
spongeforge-1.12.2-2825-7.1.6.jar

**Comment by TheFlash787** [comment]
Hey! Sorry for the delay. I notice that there's an issue with the folder that your server is in. Specifically, here: 
![image](https://user-images.githubusercontent.com/25883284/64481532-fe3a0d00-d1d4-11e9-9e86-6abe678c8dbf.png)

What is the folder name for it? Please could you send a screenshot of what you're shown when you look at the server folder.

Thank you!

**Comment by axin0452** [comment]
C:\Users\axin\Desktop\新建文件夹\config
I won't upload pictures. Sorry.

Scrambling is Chinese

**Comment by TheFlash787** [comment]
Hey! Sorry again for the delay. Would you be able to try and make the folder in English. This will allow us to see whether the code isn't a fan of the chinese. 

Thank you!

**Comment by axin0452** [comment]
[latest.zip](https://github.com/TheFlash787/Mobpression/files/3607300/latest.zip)

C:\Users\axin\Desktop\ceshi\logs

I changed the file name to ceshi.
He also makes mistakes.
The configuration file could not be generated.

**Comment by ghost** [comment]
I know this sounds dumb; but have you tried wiping and reinstalling mobpression? Because from what i can tell, the error does not make any sense
